package events

const (
	ADMIN_BROADCAST     = "ADMIN_BROADCAST"
	DEPLOYABLE_DAMAGED  = "DEPLOYABLE_DAMAGED"
	NEW_GAME            = "NEW_GAME"
	PLAYER_CONNECTED    = "PLAYER_CONNECTED"
	PLAYER_DAMAGED      = "PLAYER_DAMAGED"
	PLAYER_DIED         = "PLAYER_DIED"
	PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
	PLAYER_REVIVED      = "PLAYER_REVIVED"
	ROUND_WINNER        = "ROUND_WINNER"
	SERVER_TICK_RATE    = "SERVER_TICK_RATE"
)
